import type { Metadata } from "next";
import localFont from "next/font/local";
import { SidebarProvider, SidebarTrigger } from "./components/ui/sidebar";
import "@/globals.css";
import { AppSidebar } from "./components/appSidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {
          <SidebarProvider style={{
            "--sidebar-width": "4rem"
          }}>
            <AppSidebar />
            <main className="flex-grow">
              {children}
            </main>
          </SidebarProvider>
        }
      </body>
    </html>
  );
}
